apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-operator
  namespace: cattle-logging
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: fluentd-operator
subjects:
  - kind: ServiceAccount
    name: fluentd-operator
    namespace: cattle-logging
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: cattle-logging
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: micheliac/fluentd-base:v0.0.0.2
        imagePullPolicy: IfNotPresent
        command: ["fluentd"]
        args: ["-c", "/fluentd/etc/config/fluent.conf"]
        volumeMounts:
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - name: varlogcontainers
          mountPath: /var/log/containers
        - name: varlogpods
          mountPath: /var/log/pods
        - name: fluentdlog
          mountPath: /fluentd/etc/log
        - name: servicelog
          mountPath: /var/log/volumes
        - name: cluster-logging
          mountPath: /fluentd/etc/config/cluster
        - name: project-logging
          mountPath: /fluentd/etc/config/project
      - name: fluentd-helper
        image: micheliac/fluentd-helper:v0.0.0.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
      serviceAccountName: fluentd-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: fluentdlog
        hostPath:
          path: /var/log/fluentd
      - name: servicelog
        hostPath:
          path: /var/log/volumes
      - name: cluster-logging
        configMap:
          name: cluster-logging
          items:
          - key: cluster.conf
            path: cluster.conf
      - name: project-logging
        configMap:
          name: project-logging
          items:
          - key: project.conf
            path: project.conf